services:
  db:
    image: mariadb
    volumes:
      - ./docker-data/mariadb:/var/lib/mysql
      - ./2025_06_01_performance_osu_top_10000:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: osu
      MYSQL_USER: osu
      MYSQL_PASSWORD: osu
    ports:
      - "3306:3306"
