[project]
name = "statpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pony>=0.7.19",
    "python-dotenv>=1.2.1",
    "tqdm>=4.67.2",
]
